### PR TITLE
Link/2nd level bullet point color change for readability

### LINKED ISSUE #6: Bullet point text too dark in Minimal Markdown with Midnight
The blue and green used in the Minimal Markdown Editor for bullet points is too dark to work with in the Midnight theme. Especially the blue, but both could use a lighter color (literally, the same color but with the opposite Lightness value in HSL).

Thank you!

image

### LINKED ISSUE #7: Hyperlink text color too dark in Markdown Pro and Minimal Markdown editors
Similar to: #6 

Markdown Pro example:

image

Minimal Markdown example:

image

### PR DESCRIPTION
**Pull request by leafcutterant**
Changes the link/2nd level bullet point color to a brighter blue to have enough contrast so that it's easier on the eye.

Closes #7.

I couldn't figure out how to change the 1st level bullet point green, please add that as well in this or another PR (that would close #6). My recommendation is #01be79.

### CODE REVIEW

**Comment by atmoio** [comment]
Could you post before/after screenshots?

**Comment by leafcutterant** [comment]
@mobitar sure:

**Review by atmoio — APPROVED** [review]

**Comment by atmoio** [comment]
Looks good! Assigning to @johnny243 for deployment.

**Comment by johnny243** [comment]
Hi @leafcutterant thanks for submitting this PR! :)

> I couldn't figure out how to change the 1st level bullet point green, please add that as well in this or another PR (that would close #6). My recommendation is #01be79.

The green color comes from CodeMirror. You'll want to add a CSS rule on the editor to override it, something like this:

```css
.CodeMirror .cm-s-default .cm-variable-3 {
  color: var(--sn-stylekit-success-color) !important;
}
```

And then adjust `--sn-stylekit-success-color` to `#01be79`.

I'll submit a PR for this later.

**Pull request merged**
